using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using AutoClicker.Services.Native;

namespace AutoClicker.Services;

public class GlobalKeyboardHook : IDisposable
{
    private IntPtr _keyboardHookId = IntPtr.Zero;
    private IntPtr _mouseHookId = IntPtr.Zero;

    private readonly Win32Api.LowLevelKeyboardProc _keyboardProc;
    private readonly Win32Api.LowLevelMouseProc _mouseProc;

    private bool _isHotkeyDown = false;

    public int HotkeyVkCode { get; set; } = 0x75; // Default: F6
    public bool IsRecording { get; set; } = false;
    public bool BlockHotkey { get; set; } = true;
    public bool StopOnEscape { get; set; } = true;

    public event Action<int>? HotkeyRecorded;
    public event Action? RecordingCancelled;
    public event Action? HotkeyDown;
    public event Action? HotkeyUp;
    public event Action? EmergencyStopTriggered;

    public GlobalKeyboardHook()
    {
        _keyboardProc = KeyboardHookCallback;
        _mouseProc = MouseHookCallback;
        StartHooks();
    }

    private void StartHooks()
    {
        IntPtr hMod = IntPtr.Zero;
        try
        {
            using var curProcess = Process.GetCurrentProcess();
            using var curModule = curProcess.MainModule;
            if (curModule != null)
            {
                hMod = Win32Api.GetModuleHandle(curModule.ModuleName);
            }
        }
        catch
        {
            // fallback
        }

        // Install Keyboard Hook
        _keyboardHookId = Win32Api.SetWindowsHookEx(Win32Api.WH_KEYBOARD_LL, _keyboardProc, hMod, 0);
        if (_keyboardHookId == IntPtr.Zero)
        {
            _keyboardHookId = Win32Api.SetWindowsHookEx(Win32Api.WH_KEYBOARD_LL, _keyboardProc, IntPtr.Zero, 0);
        }

        // Install Mouse Hook
        _mouseHookId = Win32Api.SetWindowsHookEx(Win32Api.WH_MOUSE_LL, _mouseProc, hMod, 0);
        if (_mouseHookId == IntPtr.Zero)
        {
            _mouseHookId = Win32Api.SetWindowsHookEx(Win32Api.WH_MOUSE_LL, _mouseProc, IntPtr.Zero, 0);
        }
    }

    public void ResetKeyState()
    {
        _isHotkeyDown = false;
    }

    private IntPtr KeyboardHookCallback(int nCode, IntPtr wParam, IntPtr lParam)
    {
        if (nCode >= 0)
        {
            int msg = wParam.ToInt32();
            var hookStruct = Marshal.PtrToStructure<Win32Api.KBDLLHOOKSTRUCT>(lParam);
            int vkCode = (int)hookStruct.vkCode;

            if (IsRecording)
            {
                if (msg == Win32Api.WM_KEYDOWN || msg == Win32Api.WM_SYSKEYDOWN)
                {
                    if (vkCode == 0x1B) // Escape cancels recording
                    {
                        IsRecording = false;
                        RecordingCancelled?.Invoke();
                        return (IntPtr)1;
                    }

                    HotkeyVkCode = vkCode;
                    IsRecording = false;
                    HotkeyRecorded?.Invoke(vkCode);
                    return (IntPtr)1; // Swallow key used for setting hotkey
                }
            }
            else
            {
                // Emergency stop on Escape (do not swallow Escape so games/apps still get menu key)
                if (vkCode == 0x1B && StopOnEscape && (msg == Win32Api.WM_KEYDOWN || msg == Win32Api.WM_SYSKEYDOWN))
                {
                    EmergencyStopTriggered?.Invoke();
                }

                if (vkCode == HotkeyVkCode)
                {
                    if (msg == Win32Api.WM_KEYDOWN || msg == Win32Api.WM_SYSKEYDOWN)
                    {
                        if (!_isHotkeyDown)
                        {
                            _isHotkeyDown = true;
                            HotkeyDown?.Invoke();
                        }
                    }
                    else if (msg == Win32Api.WM_KEYUP || msg == Win32Api.WM_SYSKEYUP)
                    {
                        _isHotkeyDown = false;
                        HotkeyUp?.Invoke();
                    }

                    if (BlockHotkey)
                    {
                        return (IntPtr)1;
                    }
                }
            }
        }

        return Win32Api.CallNextHookEx(_keyboardHookId, nCode, wParam, lParam);
    }

    private IntPtr MouseHookCallback(int nCode, IntPtr wParam, IntPtr lParam)
    {
        if (nCode >= 0)
        {
            int msg = wParam.ToInt32();
            var hookStruct = Marshal.PtrToStructure<Win32Api.MSLLHOOKSTRUCT>(lParam);

            // Ignore simulated clicks generated by AutoClicker or injected inputs
            if (hookStruct.dwExtraInfo == AutoClickerEngine.INJECTED_SIGNATURE || (hookStruct.flags & 1) != 0)
            {
                return Win32Api.CallNextHookEx(_mouseHookId, nCode, wParam, lParam);
            }

            int vkCode = 0;
            bool isDown = false;
            bool isUp = false;

            switch (msg)
            {
                case Win32Api.WM_LBUTTONDOWN:
                    vkCode = Win32Api.VK_LBUTTON;
                    isDown = true;
                    break;
                case Win32Api.WM_LBUTTONUP:
                    vkCode = Win32Api.VK_LBUTTON;
                    isUp = true;
                    break;
                case Win32Api.WM_RBUTTONDOWN:
                    vkCode = Win32Api.VK_RBUTTON;
                    isDown = true;
                    break;
                case Win32Api.WM_RBUTTONUP:
                    vkCode = Win32Api.VK_RBUTTON;
                    isUp = true;
                    break;
                case Win32Api.WM_MBUTTONDOWN:
                    vkCode = Win32Api.VK_MBUTTON;
                    isDown = true;
                    break;
                case Win32Api.WM_MBUTTONUP:
                    vkCode = Win32Api.VK_MBUTTON;
                    isUp = true;
                    break;
                case Win32Api.WM_XBUTTONDOWN:
                    uint xbtnDown = (hookStruct.mouseData >> 16) & 0xFFFF;
                    vkCode = xbtnDown == 1 ? Win32Api.VK_XBUTTON1 : Win32Api.VK_XBUTTON2;
                    isDown = true;
                    break;
                case Win32Api.WM_XBUTTONUP:
                    uint xbtnUp = (hookStruct.mouseData >> 16) & 0xFFFF;
                    vkCode = xbtnUp == 1 ? Win32Api.VK_XBUTTON1 : Win32Api.VK_XBUTTON2;
                    isUp = true;
                    break;
            }

            if (vkCode != 0)
            {
                if (IsRecording)
                {
                    if (isDown)
                    {
                        // If Left Click, check if the user clicked inside our application window
                        if (vkCode == Win32Api.VK_LBUTTON)
                        {
                            IntPtr hWndUnderMouse = Win32Api.WindowFromPoint(hookStruct.pt);
                            Win32Api.GetWindowThreadProcessId(hWndUnderMouse, out uint procId);
                            if (procId == (uint)Environment.ProcessId)
                            {
                                // Let normal UI button click proceed
                                return Win32Api.CallNextHookEx(_mouseHookId, nCode, wParam, lParam);
                            }
                        }

                        HotkeyVkCode = vkCode;
                        IsRecording = false;
                        HotkeyRecorded?.Invoke(vkCode);
                        return (IntPtr)1; // Swallow mouse click used for setting hotkey
                    }
                }
                else
                {
                    if (vkCode == HotkeyVkCode)
                    {
                        if (isDown)
                        {
                            if (!_isHotkeyDown)
                            {
                                _isHotkeyDown = true;
                                HotkeyDown?.Invoke();
                            }
                        }
                        else if (isUp)
                        {
                            _isHotkeyDown = false;
                            HotkeyUp?.Invoke();
                        }

                        if (BlockHotkey)
                        {
                            return (IntPtr)1;
                        }
                    }
                }
            }
        }

        return Win32Api.CallNextHookEx(_mouseHookId, nCode, wParam, lParam);
    }

    public void Dispose()
    {
        if (_keyboardHookId != IntPtr.Zero)
        {
            Win32Api.UnhookWindowsHookEx(_keyboardHookId);
            _keyboardHookId = IntPtr.Zero;
        }

        if (_mouseHookId != IntPtr.Zero)
        {
            Win32Api.UnhookWindowsHookEx(_mouseHookId);
            _mouseHookId = IntPtr.Zero;
        }

        GC.SuppressFinalize(this);
    }

    ~GlobalKeyboardHook()
    {
        Dispose();
    }
}
